### ISSUE TITLE
Troubleshooting custom extension

### ISSUE THREAD

**Issue by mycodeself** [tgalopin/html-sanitizer-bundle#6] opened 2019-03-28 08:16 UTC
Im having problems with a custom sanitizer extension that i created for a project im working on. The extension is manually register with the tag name using YAML like this:

```
    app.sanitizer.iframe_custom:
        class: App\Sanitizer\CustomIframeExtension
        tags:
          - { name: html_sanitizer.extension }
```
The problem its that this extension is not register though the sanitizer builder.

I debug the code and i found that in the HtmlSanitizerExtension when it call to "findTaggedServiceIds('html_sanitizer.extension')" my sanitizer extension service its not found.

If i debug my kernel, and use the findTaggedServiceIds('html_sanitizer.extension') in my Kernel.php its found the service by tag... its like when HtmlSanitizerExtension is loaded my services arent currently loaded.

Some suggestion of what can i do?

Thanks and regards!

**Comment by tgalopin** [comment] 2019-04-02 15:12
Hello @mycodeself,

Sorry I missed this issue.

This is strange. Which version of Symfony are you using?

**Comment by stof** [comment] 2019-04-17 14:39
@tgalopin this is actually not strange at all. DI extensions run on an isolated ContainerBuilder. the goal is precisely to prevent such mistake which would only load services from bundles registered earlier. With this isolation, external services are inaccessible whatever the order of bundles is.

Finding tagged services to register extensions must be done in a compiler pass, not in the DI extension.

**Comment by tgalopin** [comment] 2019-04-17 15:33
Thanks @stof, closing this issue then.

@mycodeself if you want to do this, you can use the kernel as a compiler pass as well (https://symfony.com/blog/new-in-symfony-3-4-defining-compiler-passes-in-the-kernel)

**Comment by stof** [comment] 2019-04-17 15:46
@tgalopin the issue is that **this bundle** is doing the `findTaggedServiceIds('html_sanitizer.extension')` in the DI extension. So this issue should not be closed. It should be fixed. This bundle needs to be using a DI extension.

**Comment by tgalopin** [comment] 2019-04-17 15:49
Ah, my bad. Let's do this :) .

**Closed as completed** 2019-04-18 13:12 UTC
